uwblueprint/ccbc

- README.md
No ticket, just fixing a typo in the README vault instructions
> update vault instructions in README

- backend/typescript/migrations/create_users_table.ts
- backend/typescript/models/user.model.ts
- backend/typescript/types.ts
[Update users table and model](https://www.notion.so/uwblueprintexecs/Update-Users-Table-Model-1a4796a825474df08dba0ee21f58116b)
* update user.model.ts, types.ts
* create create_users_table migration file
1. ensure table has been created by looking at https://github.com/uwblueprint/ccbc/#accessing-postgresql-database
*
> Update Users Table and Model

- .github/workflows/ci-frontend.yml
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/EntityAPIClient.ts
- frontend/src/components/auth/Logout.tsx
- frontend/src/components/auth/RefreshCredentials.tsx
- frontend/src/components/crud/CreateForm.tsx
- frontend/src/components/crud/DisplayTableContainer.tsx
- frontend/src/components/crud/UpdateForm.tsx
- frontend/src/components/pages/__tests__/Default.test.tsx
Configure Frontend CI (https://www.notion.so/uwblueprintexecs/Configure-CI-frontend-7a9ddfb6bb1e4732990c393ebc06bed0)
* Configured frontend CI
* Linted frontend directory
1. Verify that workflows correctly
*
> Configure Frontend CI

- backend/typescript/middlewares/validators/entityValidators.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/emailService.ts
- backend/typescript/services/implementations/entityService.ts
- backend/typescript/services/implementations/fileStorageService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/utilities/errorResponse.ts
Fixed bug where error.message was giving typescript errors as they should be handled with type unknown. Explicitly checking type should fix that.
* 
1.
*
> Modify routes to catch errors with type unknown

- frontend/src/components/auth/Login.tsx
- frontend/src/theme/index.tsx
* Disabled scroll
* Made the font size for heading and body a bit smaller (it looked too big lol)
* Moved button styling to theme (fyi did not find input to have enough styling to be put into the theme)
> Few styling additions to login page

- backend/typescript/testUtils/testDb.ts
- backend/typescript/utilities/dbUtils.ts
* Altered test db url to use the test db rather than main db
> Change test db url to correct version

- frontend/src/APIClients/ReviewAPIClient.ts
> Updated review types on frontend

- frontend/src/components/auth/Login.tsx
[Pressing Enter Doesn't Login](https://www.notion.so/uwblueprintexecs/Pressing-Enter-doesn-t-login-829f2f3a5a6647d49c5f2caaf94d716d)
* Added onKeyPress event to FormControl
1. Write valid/invalid credentials into login input fields and click Enter to log in
* Clicking Enter triggers Login button
> Logging In on Enter

- frontend/src/components/common/InviteAdminModal.tsx
- frontend/src/components/common/NavBar.tsx
- frontend/src/constants/ErrorMessages.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Invite-New-Admin-Flow-0233d07d955442b0b3d7005790dcedcd)
* implemented Invite New Admin modal
1. Invite an admin
2. Inspect the reponse and confirm that a valid token was returned in the response body
*
> added invite admin modal

- frontend/src/components/pages/AdminDashboard/AdminDashboard.tsx
[Create Review Page: Link to Admin Dashboard](https://www.notion.so/uwblueprintexecs/Create-Review-Page-Link-to-Admin-Dashboard-8776ffff09cd493c8763bda1785b9dad)
* Add link to go to the Create Review Page from the Admin Dashboard
1. Go to Admin Dashboard
2. Click on the "+ Add Review" button at the upper right hand corner
3. You should be at the Create Review Page now! 
*
> Add Link to /create-review from Admin Dashboard

- frontend/src/components/pages/AdminDashboard/AdminDashboard.tsx
- frontend/src/types/ReviewTypes.ts
- frontend/src/utils/MappingUtils.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Title-not-displaying-on-Admin-Dashboard-6de0900938374310915eccdb954ba7eb)
* Changed ReviewResponse in ReviewTypes.ts to match IReviewService on the series field  
1. Create a review with the given fields ` {
"body": "4",
"createdBy": 1,
"byline": "Hello New Review",
"featured": true,
"publishedAt": 12445,
"books": [
{
"title": "Book1 Title",
"coverImage": "Book1 cover Image",
"titlePrefix": "Book1 Title Prefix",
"seriesOrder": "1",
"illustrator": ["illustrator1"],
"translator": ["translator1"],
"formats": [
{
"format": "format1",
"price": "$15.0",
"isbn": "1234-5678-931"
}
],
"minAge": 3,
"maxAge": 18,
"authors": [
{
"fullName": "Insert Author Full Name",
"displayName": "Insert Author Display Name",
"attribution": "Insert Author …
> fixed bug where review title wasn't showing in dashboard

- frontend/src/APIClients/BaseAPIClient.ts
[Doesn’t force logout upon token expiry?](https://www.notion.so/uwblueprintexecs/Doesn-t-force-logout-upon-token-expiry-e4a42d1e4f234e81b951eaaf1342ade2)
* Fixes an issue with the refresh token not being set in local storage upon refresh
1. Try making a request with an expired token
2. Retry making the request. Your token should be valid now and the request should work
* Just test the change to make sure it works as expected- thanks!
> Fixes auth refresh token issue

- frontend/src/components/pages/AdminDashboard/AdminDashboard.tsx
- frontend/src/types/ReviewTypes.ts
[Preview Review Modal: Link with Admin Dashboard](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=49acbbd45ce941dba43f036a8033fe7b)
* Just took the data from the backend ReviewResponse object and passed it to the previewModal component
1. Create a review 
2. Go to the admin dashboard
3. Click the eye icon -> the preview modal should open with all the info
* Testing + passing the data from the adminDashboard to modal
> Preview Review Modal: Link with Admin Dashboard

- frontend/src/components/pages/AdminDashboard/AdminDashboard.tsx
- frontend/src/components/pages/CreateReview/BookModal.tsx
[Edit Review: Link with Admin Dashboard](https://www.notion.so/uwblueprintexecs/Edit-Review-Link-with-Admin-Dashboard-2535080446bc41a6a9b152e4cf15a958)
* added useHistory to navigate to edit review page
1. add a review to your database by creating a review
2. go to admin dashboard and click on the edit button for that review
3. you should be navigated to the edit-review page with the information pre-filled
* Also changed a little bug on the BookModal where the price was not being preset correctly
> Links edit button to edit-review page from the dashboard

- frontend/src/components/pages/CreateReview/mockData.ts
* 
1. Try to make a review
2. Edit the sample book provided
3. You should see the ISBN is properly formatted in the modal
*
> fixes ISBN in mock book data

- frontend/src/APIClients/ReviewAPIClient.ts
- frontend/src/components/pages/CreateReview/CreateReview.tsx
- frontend/yarn.lock
[Ticket Name](https://www.notion.so/uwblueprintexecs/Edit-Review-Publish-Edited-Review-71363e780fb049ffa7eda5d3d75db44e)
* 
1. Create a review and publish it
2. Edit review
3. Open the network tab
4. Publish the review
5. Verify that a PUT request has been sent and successful
6. Verify that the database has the right values of the fields
*
> implemented publish edited review functionality

- backend/typescript/server.ts
> [Hotfix] Allow CLIENT_HOST for Cross Origin Requests 

- .github/workflows/firebase-hosting-merge-prod.yml
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- frontend/src/utils/Firebase.ts
* Frontend firebase config was previously hard-coded in `Firebase.ts`
* We need different configs for staging/prod so I moved this to an env variable
1. Pull secrets
2. On the frontend, go to `/signup` and create a new user, ensure that the signup flow works as normal
3. We can't really test the CI job until we merge :cry: 
* Typos, etc in the `.yml` files
> [Hotfix] Moved Firebase config to env vars

- .github/workflows/firebase-hosting-merge-prod.yml
- .github/workflows/firebase-hosting-merge.yml
- frontend/src/utils/Firebase.ts
> [Hotfix] Add Prod Configuration For Firebase

- .github/workflows/firebase-hosting-merge-prod.yml
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- frontend/src/utils/Firebase.ts
> [Hotfix] Prepend REACT_APP to Env Variables

- backend/typescript/services/implementations/reviewService.ts
[Ticket Name]()
* added review_id as a filter from the database query
1. Add a review with a book
2. Add a second review with a book
3. Edit the second review
4. Make sure the first review books are still there
*
> [HOTFIX] Fixed Deleting of Books when Editing another Book

- frontend/src/APIClients/BaseAPIClient.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Doesn-t-force-logout-upon-invalid-auth-token-e4a42d1e4f234e81b951eaaf1342ade2)
* 
1.Login as normal
2. Invalidate your token by adding a few chars
3. reload the page
4. confirm that you've been logged out
*
> [Hotfix] [TEMP] Logout Upon Invalid Auth Token

- frontend/src/constants/Enums.ts
[Correct Field Names](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=fd96a04b66f7458d8e284ff5d1db139e)
* Changed Paperbound to Paperback
* Changed e-Book to eBook
1.
*
> Correct field names

- frontend/src/components/pages/CreateReview/CreateReview.tsx
[Loading Screen: Publish Review](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=c3b3160c80df40bd8040ce0308ec5b74)
* added loading screen when user is publishing
1. create a review, then publish it and verify that loading screen is present.
2. edit a review, publish it, and verify that loading screen is present.
*
> [Feat]: Loading Screen Publish Review

- frontend/src/components/PreviewReview/PreviewReviewModal.tsx
- frontend/src/components/pages/CreateReview/CreateReview.tsx
[Preview Review Modal: Link to Create/Edit Page](https://www.notion.so/uwblueprintexecs/Preview-Review-Modal-Link-to-Create-Edit-Page-acf011991df744a19b75b96837fb87d5)
* added `PreviewReviewModal` component to `CreateReview` page that opens when you click Preview button on top right
* Preview button is disabled if review body, reviewer byline, or books are empty
1. Go to Admin Dashboard and test opening preview modal
2. Navigate to editing an existing review and test the following:
- open preview modal and check that it matches one from admin dashboard
- remove reviewer byline and verify preview button is disabled
- remove review body and verify preview button is disabled
- remove all books and verify preview button is disabled
3. Create a new review and do the following above steps again …
> [Feat] Preview Review Modal: Link to Create/Edit Page

- README.md
Update Migration instructions and add help link
> Update Migration instructions and add help link

- backend/typescript/migrations/20220621024341-user_givecloud_subscription_migration.js
- backend/typescript/migrations/20220622224714-user_givecloud_subscription_migration.js
- backend/typescript/models/user.model.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/services/implementations/__tests__/userService.test.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/swagger.yml
- backend/typescript/types.ts
[Update User model to include subscription_expires_on](https://www.notion.so/uwblueprintexecs/Update-User-model-to-include-subscription_expires_on-7cb0479ae51b4723adc6fd31640c5ca4)
* Deleted active from the users modal and db
* Added subscription_expires_on to user modal and db
1. Verify that the migration works up and down 
2. Verify website still functions in terms of things related to users such as in admin dashboard
> [Tech] Update User model to include subscription_expires_on

- frontend/src/App.tsx
- frontend/src/components/PreviewReview/PreviewReview.tsx
- frontend/src/components/pages/DisplayReview/DisplayReview.tsx
- frontend/src/constants/Enums.ts
- frontend/src/constants/Routes.ts
[Review base page](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=683343a432524356b66129c98a903cbe)
* added new frontend page and routes at `/reviews/:id` accessible by Admins, Subscribers, and Creators
* added loading state for when review is being loaded
* if review does not exist/error, redirects to 404
1. Go to `localhost:3000/reviews/ID` where `ID` is a review id that currently exists (you can find these by editing existing reviews and looking at the url)
2. Verify that page works and matches [figma designs](https://www.figma.com/file/kEa0TbJ5VKAmI97eGefXs6/Magazine-Review---Subscriber-Experience?node-id=467%3A1729 ) approx.
3. Input a ID that doesn't exist for `localhost:3000/reviews/ID` and verify that it redirects to …
> [Feat] Review base page

- frontend/src/components/pages/CreateReview/BookModal.tsx
- frontend/src/utils/MappingUtils.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Fix-Submitting-Invalid-Price-Crash-eaabb56840224e5abf544aea314621fa)
* 
1. Use an existing review (previously seeded data)
2. Submit
*
> [Bug] Fix Submitting Invalid Price Crash

- frontend/src/components/pages/CreateReview/AddSelectList.tsx
- frontend/src/components/pages/CreateReview/AddStringInputList.tsx
- frontend/src/components/pages/CreateReview/BookModal.tsx
- frontend/src/components/pages/CreateReview/InputField.tsx
[Multiple formats: book modal](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=a38e0ebe769046eea158057068fc66e2)
* Added functionality of adding/deleting more formats for books
1. Create a book and add/delete multiple formats
2. Verify that you cannot add another format if one format is currently not completely filled
3. Verify that you cannot submit the book if one format is not currently completely filled
4. Edit an existing book and add formats
* for the functionality of this ticket, there is no error message if the inputted price is above the max price BUT the button to submit the book will be disabled
> [Feat]: Multiple formats: book modal

- frontend/src/App.tsx
- frontend/src/components/pages/MockSearch/MockSearchPage.tsx
- frontend/src/components/pages/MockSearch/ReviewThumbnail.tsx
- frontend/src/components/pages/MockSearch/mockReviews.ts
- frontend/src/constants/Routes.ts
- frontend/src/theme/index.tsx
[Individual Review Thumbnail Component](https://www.notion.so/uwblueprintexecs/Individual-Review-Thumbnail-Component-73b75f1d3b8f4901a8e565445fcc554b)
* Made a mock page called mock-search-page with everything
* Four mock thumbnails are on the page: one with normal title length and normal author length, one with long title, one with long author, and one with both long title and author
1. Go to [http://localhost:3000/test/mock-search-page](http://localhost:3000/mock-search-page)
2. 1st review: 1 book with normal length title + 1 author
3. 2nd review: 2 books with series name "Harry Potter" + multiple authors that overflow
4. 3rd review: 1 book with long title + multiple authors
* matches figma designs https://www.figma.com/file/kEa0TbJ5VKAmI97eGefXs6/Magazine-Review---Subscriber-Experience? …
> Individual Review Thumbnail Component

- frontend/src/components/pages/CreateReview/CreateReview.tsx
As per https://github.com/uwblueprint/ccbc/pull/101#issuecomment-1146869414, fixing toast statuses
1. Create a new review, upon publish a green toast appears
2. Edit a review, upon publish a blue toast appears
> [Bug] Fix Toast Status on Publish to Always Display Success

- frontend/src/components/pages/CreateReview/BookModal.tsx
[Submit book with no author](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=e04fdda4e01340ca82193984c8d288e5)
* Verify that all authors are non empty in order for book to be submitted
1. Add a new book to a review with all required fields filled in EXCEPT for author. Verify that you cannot submit book.
2. Add a new author and don't input any text. Verify that you cannot submit book.
3. Add author text and verify that you can submit book.
4. Continue ^ with more / less authors 
5. Ensure that submitting review still works
*
> [Bug] Submit book with no author

- backend/typescript/middlewares/auth.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/services/interfaces/authService.ts
- backend/typescript/services/interfaces/userService.ts
[Subscription Check Middleware](https://www.notion.so/uwblueprintexecs/Subscription-Check-Middleware-ab15d80c58424e7e85fc6c64fc26f84b)
*  when users make a request, the middleware compares the user's subscription_expires_on date with the current date. If the subscription expiration date passed, the user is logged out. Else, the request is authorized. 
1. create a new user and set its role_type to any role that is not Admin
2. create a user with a `subscription_expires_on` date that passed, and test that it is logged out, with the 401 error msg
3. create a user with a `subscription_expires_on` date that did not pass, and test that no error occurs and make a request, check that it went through and no error msg
4. create a user with a `subscription_expires_on` date that is null, and test …
> [Feat] Check if user subscription has expired in middleware 

- frontend/src/components/PreviewReview/PreviewReview.tsx
[Fix incorrect "reviewed by" field](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=8ac1bee48f204d7b901c3cf099ce32ef&pm=c)
* changed so it displays review byline instead of reviewer name
1. Go to an existing review and preview it on admin dashboard. Verify that reviewed by field shows the review byline.
2. Create a new review and preview it. Verify that the preview matches the review byline.
*
> [Bug] Fix incorrect "reviewed by" field

- frontend/src/components/pages/CreateReview/ReviewEditor.tsx
[Block Adding Images to Review](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=a7884ed6ece74d06a3aae706fb1facee&pm=c)
> [fix]: Block Adding Images to Review

- backend/typescript/services/implementations/authService.ts
> [Fix] removed console logs

- frontend/src/App.tsx
- frontend/src/components/pages/CreateReview/AddMultiSelect.tsx
- frontend/src/components/pages/CreateReview/BookModal.tsx
- frontend/src/components/pages/FilterBox.tsx
- frontend/src/constants/Routes.ts
[Filter Function - Filter Boxes Component](https://www.notion.so/uwblueprintexecs/Filter-Function-Filter-Boxes-Component-6df327e0766947de894a776cdc409665)
* Note that the design of the filter box is not included in this ticket
* Created the filter box component with two filters applied
* audience: single select filter
* genres: multi-select filter
1. Instead of passing options to choose from in the dropdown menu of both filters as a prop, hardcode two arrays of options and test with your arrays 
2. verify that the audience is single-select
3. verify that genres is multi-select
4. verify that `genres`  and `age` has the correct value 
5. verify that when clear is clicked, both `genres` and `age` are cleared and the filter box is cleared
6. **note**, the only way to test the apply button is …
> [Feat] Create Filter Box Component

- frontend/src/APIClients/ReviewAPIClient.ts
- frontend/src/components/pages/SearchReviews/ReviewsGrid.tsx
- frontend/src/components/pages/SearchReviews/SearchReviews.tsx
[Review Search - Integration](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=26e4a32aefc146389df47736fbd5c856&pm=c)
* added additional parameters `search`, `size` and `page` to `getReviews` function in ReviewAPIClient.
* calls search endpoint to fetch reviews when updated query
* sort review books so thumbnail always displays first book in series
1. Go to http://localhost:3000/magazine/search_results/ and verify that books are displayed
2. Search up by author name, book name, etc and verify that books are displayed
3. Verify that first book in series for review is shown in thumbnail
*
> [Feat] Review Search - Integration

- frontend/src/components/pages/SearchReviews/ReviewThumbnail.tsx
- frontend/src/components/pages/SearchReviews/ReviewsGrid.tsx
[Redirect Thumbnail Click](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=08eca47ac54e49a794d841ea5acefdde&pm=c)
* made thumbnails clickable and redirect to display review page for associated review
1. Go to http://localhost:3000/magazine/search_results and verify that thumbnail image and book title can be clicked. It should redirect to http://localhost:3000/reviews/{REVIEW ID} 
*
> [Feat] Redirect Thumbnail Click

- backend/typescript/services/implementations/reviewService.ts
[Reviews Endpoint: Sorting](https://www.notion.so/uwblueprintexecs/Reviews-Endpoint-Sorting-63cc04869ebb43b1b2f5efe33cc46eac)
* sorts by published_at then updatedAt
> [Feat]: Reviews Endpoint: Sorting

- frontend/src/components/PreviewReview/PreviewReview.tsx
[Change By to by](https://www.notion.so/uwblueprintexecs/Change-By-to-by-6560125745f3492da387706a0a8727fd)
> [Bug] Change By to by

- frontend/src/components/pages/CreateReview/CreateReview.tsx
[Published Status is Incorrect](https://www.notion.so/uwblueprintexecs/Published-Status-is-Incorrect-e4a4f9de7f214df28db4721f07c04b8d)
* gets publishedAt value dynamically
1. while creating review, hit previous before you save or submit
2. verify it says draft in top-left of modal
> [Bug] Published Status is Incorrect

- frontend/src/App.tsx
[Disable /signup route](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=0f0df1f1b7074d2cb19b7eb7652d7d04&p=f14ccc2bb7f245dc9d152f16f410933b&pm=c)
* hid /signup route behind the NODE_ENV variable
* directed to signup page if development environment otherwise redirected to unauthorized page
1. Docker compose and check if /signup route still works
2. Alter frontend docker file to match image below so it builds in production mode
3. Docker compose and check /signup route doesn't work
* signup route works only in development environment
> [Fix]: Disabled Signup Route in Production

- backend/typescript/rest/givecloud.ts
[Givecloud Security](https://www.notion.so/uwblueprintexecs/Givecloud-Security-5533679ef57c498e97ad7e86edfa9b26)
* Used HMAC Secret Key for hashing to secure givecloud
1. Add `HMAC_SECRET_KEY` to `.env`
* Still need to verify with Givecloud API. Waiting on auth.
> Givecloud HMAC Hashing

- .github/workflows/firebase-hosting-merge-prod.yml
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- frontend/src/components/pages/CreateReview/AddMultiSelect.tsx
- frontend/src/components/pages/FilterBox.tsx
- frontend/src/components/pages/SearchReviews/SearchReviews.tsx
- frontend/src/constants/Enums.ts
[Filter Base Page](https://www.notion.so/uwblueprintexecs/Filter-Base-Page-db301040f994483388abec0906627633)
* Implemented existing FilterBox and AddMultiSelect components using searchStyle flag for differentiating styles
* Updated style with react creatable library features to display applied filters 
[Screen Recording 2022-09-26 at 7.31.57 PM.zip](https://github.com/uwblueprint/ccbc/files/9650274/Screen.Recording.2022-09-26.at.7.31.57.PM.zip)
1. Visit Home Scream
2. Click Search
3. Filter boxes are located here for testing
*
> [Feat]: add frontend filter components

- backend/typescript/middlewares/validators/creatorValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/rest/creatorRoutes.ts
- backend/typescript/server.ts
- backend/typescript/services/implementations/creatorService.ts
- backend/typescript/services/interfaces/creatorService.ts
- backend/typescript/types.ts
[Setup Creators on the Backend](https://www.notion.so/uwblueprintexecs/Setup-Creators-on-the-Backend-fbf4257d3aa3494b9519522cb64d8005)
* Read Ticket on Notion
1. Make Postman Request as shown below:
> More Creator Backend Setup

- frontend/src/components/PreviewReview/PreviewInfo.tsx
- frontend/src/constants/Enums.ts
[ISBN, Format, Price changes](https://www.notion.so/uwblueprintexecs/ISBN-Format-Price-changes-6e52bad315c14b3d900310d85df95cad)
* Converting long form formats to short form using an object with translations
1. Create a new hardcover book or audio book
2. Look at the preview and see that the format is either (hc) or (ab) depending on type of book
3. Make sure order is IBSN, Format, then Price
* N/A
> change IBSN, Format, Price in preview

- backend/typescript/middlewares/validators/userValidators.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/services/implementations/userService.ts
- frontend/src/APIClients/UsersAPIClient.ts
- frontend/src/App.tsx
- frontend/src/components/auth/SubscriberSignup.tsx
- frontend/src/constants/Routes.ts
[Subscriber Signup Page](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=0f0df1f1b7074d2cb19b7eb7652d7d04&p=ee14c6573636443aa1de9765e687946e&pm=c)
* created new route called subscriber signup
* created new UsersAPIClient that creates a new user that is set to the subscriber role
1. Go to /subscriber-page route
2. Enter new email and signup
* Decisions made in the userRoutes and userServices file
> [Feat]: New signup page

- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/creatorRoutes.ts
- backend/typescript/services/implementations/creatorService.ts
- backend/typescript/services/interfaces/creatorService.ts
[Approve Creators Route](https://www.notion.so/uwblueprintexecs/Approve-Creators-Route-cbd6c5cc12a94da3ae64e644a47e80ca)
* Check if admin
* If admin approve by id
* used RESTful URL (`/approve/:id`)
1. Try to approve a creator without admin
2. Try to approve a creator with admin
3. Check database if the user is an approved creator
* Whether or not these changes propagate to the database
> Add route for approving creators.

- backend/typescript/middlewares/validators/creatorValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/rest/creatorRoutes.ts
- backend/typescript/services/implementations/creatorService.ts
- backend/typescript/services/interfaces/creatorService.ts
[POST Creators Route](https://www.notion.so/uwblueprintexecs/POST-Creators-Route-77edec073fcf4ab9b93106fb859163b3)
*  In creator services, add a createCreator method that accepts a CreatorCreateUpdateDTO and adds it to the databse
* implemented a post route in creatorRoutes to create a creator
1. the database updates with new creator 
2. the post route works
*
> [Feat] post creators route

- frontend/src/APIClients/UsersAPIClient.ts
- frontend/src/components/common/NavBar.tsx
- frontend/src/components/pages/AdminDashboard/AdminDashboard.tsx
[Blank Field- Admin Dashboard](https://www.notion.so/uwblueprintexecs/Blank-Field-Admin-Dashboard-55e7453c63b74b7899168014f43c49a3)
* 
1.
*
> [BUG] Change actions column for admin dashboard

- frontend/src/APIClients/ReviewAPIClient.ts
- frontend/src/components/pages/FilterBox.tsx
- frontend/src/components/pages/SearchReviews/SearchReviews.tsx
[Filter Functionality](https://www.notion.so/uwblueprintexecs/Filter-Functionality-0e37ca52ebbc45cbbaa2939043b10bcb)
* Updated Review API Client to include genres parameter
* Passed in genres and age parameters to get request
* Updated filters to sync with search query
1. Navigate to search page
2. Try filtering different age groups + genres
*
> [Bug]: Fix Filter Functionality

- backend/typescript/rest/givecloud.ts
[Change Givecloud Hook to using new signup flow] (https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)](https://www.notion.so/uwblueprintexecs/Change-Givecloud-Hook-to-using-new-signup-flow-b6dc2ec256604c15802566df42441c9f)
* 
1.
*
> Change givecloud hook

- frontend/src/APIClients/UsersAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/SubscriberSignup.tsx
- frontend/src/components/auth/SuccessfullyCreatedEmailModal.tsx
[Subscriber Signup Completion](https://www.notion.so/uwblueprintexecs/Subscriber-Signup-Completion-e6115dac2b4f4ef7bed9508210cda343)
* Added signup link to login page
* Handled account creation success and fail on frontend 
1. Use button on login page to go to signup page
2. Create an account with an invalid email address to see error message and highlighting
3. Create an account with valid email address to see success modal 
* Account creation with fail and success
> Subscriber Signup

- backend/typescript/middlewares/validators/creatorValidators.ts
- backend/typescript/rest/creatorRoutes.ts
- backend/typescript/services/implementations/creatorService.ts
- backend/typescript/services/interfaces/creatorService.ts
- frontend/src/APIClients/CreatorAPIClient.ts
- frontend/src/types/CreatorTypes.ts
[Creator Frontend + Backend Changes and stitching](https://www.notion.so/uwblueprintexecs/Creator-Frontend-Backend-Changes-and-stitching-49a45413e4234ff69f8a0f31eb9b4774)
* Added creator types (Creator, Presentation, Publication, CreatorRequest) in frontend/src/types/CreatorTypes 
* Added updateCreator method in backend + exposed it in route /creators/<id>
* Modified createCreator method to take in only userId
* Added CreatorAPIClient.ts for updateCreator and createCreator functions
* Updates to createCreator method on backend
* CreatorAPIClient updateCreator, createCreator functions
> Creator Frontend + Backend Changes and Stitching

- frontend/src/assets/checkmark-active.svg
- frontend/src/assets/checkmark-inactive.svg
- frontend/src/components/pages/CreatorProfile/AvailabilityForm.tsx
- frontend/src/components/pages/CreatorProfile/CreatorInputField.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfileForm.tsx
- frontend/src/types/CreatorProfileTypes.ts
[Creator Profile: Availability form](https://www.notion.so/uwblueprintexecs/Creator-Profile-Availability-form-914e3ce963084686bbbbe69c952814c2?pvs=4)
* Geographic reach 
* Primary timezone
* General availability
1. Navigate to /create-creator-profile and ensure that form selection works and required fields stop user from submitting if empty
* General availability component, as it is a custom implementation
> Add Creator Availability Form

- backend/typescript/rest/creatorRoutes.ts
- backend/typescript/services/implementations/creatorService.ts
- backend/typescript/services/interfaces/creatorService.ts
- frontend/src/APIClients/CreatorAPIClient.ts
- frontend/src/components/pages/CreatorDirectory/CreatorFilterBox.tsx
- frontend/src/components/pages/CreatorDirectory/SearchCreators.tsx
- frontend/src/constants/Enums.ts
[Booker: Creator Directory Search](https://www.notion.so/uwblueprintexecs/Booker-Creator-Directory-Search-2d7bb41a8c0e44b7aeb174893366f961?pvs=4)
* Added CreatorFilterBox for filtering logic mimicking review filters
* Updating API client for new filtering params
1. Pull branch and navigate to creator directory
2. Test filtering and search with mock data
*
> [Feat]: add creator directory search and filtering

- frontend/src/components/auth/SetPassword.tsx
- frontend/src/components/common/ChangePassword/ChangePasswordModal.tsx
- frontend/src/components/common/ChangePassword/PasswordRequirements.tsx
[Password Error](https://www.notion.so/uwblueprintexecs/Password-Error-d826222ef33c4a55beb3fe3afc4856b5)
* Password requirements now being shown to the user
* Specific error message now being shown when the password is too weak
1. **Admin new password setup**: Make an admin account, follow email verification steps, enter a too-short password
2. **Subscriber new password setup**: Make a subscriber account, follow email verification steps, enter a too-short password
3. **Reset password**: Go to [http://localhost:3000/forgot-password](http://localhost:3000/forgot-password), enter existing account email, follow reset instructions from email, enter a too-short password
4. **Change password**: Log in with admin account, click on profile icon > Change Password, enter a too-short password
*
> Display password requirements and detailed password error message

- backend/typescript/services/implementations/authService.ts
- frontend/src/components/auth/SetPassword.tsx
[Creator Signup Flow Fixes](https://www.notion.so/uwblueprintexecs/Creator-Signup-Flow-Fixes-1251dfcc5e074641a9bdeeaef06178e2)
* Added a check to redirect creators to` finish-profile` page
* Fixed minor grammar issue on the email sent to new sign-ups
1. Go to `creator-signup` and make a new account
2. Go to your email to get the password setup link
3. Make a password and check if you are redirected to the right page
*
> Fix signup bugs

- frontend/src/components/pages/CreatorProfile/CreatorProfile.tsx
[Booker/Subscriber Flow: Related Reviews button](https://www.notion.so/uwblueprintexecs/Booker-Subscriber-Flow-Related-Reviews-button-4cfd5259c4d4437d92c231396af8fe9c)
* Added UI for Related Reviews button and linked it to the search page pre-filled with the author name as the search query
1. Go to http://localhost:3000/creators/1
2. Click on the Related Reviews button
*
> Implement related reviews button

- frontend/src/constants/Enums.ts
[New Category: Board Books](https://www.notion.so/uwblueprintexecs/New-Category-Board-Books-ec7eb08c536148e3b2c3d9854b834c24)
* Added "Board Books" to the value options for a SelectList that is used when adding books. 
* The result is that Board books should be an option when choosing a new book's format.
1. Log on to the platform
2. Try to add a book as an admin
3. Choose the format and check if Board books is an option
* NOTE: I was not able to test because my docker broke (see discord) and I can't run the application. However, this seems like a simple enough change that we can push it. Waiting until I fix my docker might be an unnecessary blocker. Please test on your end.
- [] I have run docker-compose up and my project compiled
> Add board book category

- backend/typescript/middlewares/validators/creatorValidators.ts
- backend/typescript/rest/creatorRoutes.ts
- backend/typescript/services/implementations/creatorService.ts
- backend/typescript/services/interfaces/creatorService.ts
- backend/typescript/types.ts
- frontend/src/APIClients/CreatorAPIClient.ts
- frontend/src/components/pages/CreatorProfile/AvailabilityForm.tsx
- frontend/src/components/pages/CreatorProfile/ContactInfoForm.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfileForm.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfileNav.tsx
- frontend/src/components/pages/CreatorProfile/GeneralInfoForm.tsx
- frontend/src/components/pages/CreatorProfile/Publications Form/BibliographyDragAndDrop.tsx
- frontend/src/components/pages/CreatorProfile/Publications Form/PublicationsForm.tsx
- frontend/src/components/pages/CreatorProfile/SubmittedCreatorProfile.tsx
- frontend/src/types/CreatorProfileTypes.ts
- frontend/src/types/CreatorTypes.ts
[Creator Profile: Multi-step form](https://www.notion.so/uwblueprintexecs/Creator-Profile-Multi-step-form-ad603a8fc07a43d0a7bac478a22e553c?pvs=4)
* Overall connect the creator profile to the backend but very huge PR so generally
* When user first saves/submits the form it checks if the creator object exists for this user id - if so it updates the existing creator object otherwise creates a new object and updates
* For every save isReadyForReview is marked as false but for submission it is marked as true and shows up in the admin dashboard for review
* The creator-profile form is continually accessible after submit for updates (not sure when this should be closed)
* A modal is used for submission confirmation + toasts for saves / errors
* Upon load of the form if the user has saved data …
> Connect creator profile form to backend

- frontend/src/components/pages/CreatorProfile/CreatorProfileForm.tsx
- frontend/src/components/pages/CreatorProfile/ReviewForm.tsx
[Creator Profile: Review Form](https://www.notion.so/uwblueprintexecs/Creator-Profile-Review-form-5b09aa6313ec43fbb05c20f033cef1df?pvs=4)
* Added review form using creator profile context
* Uses Chakra Accordion and maps through creator data to display each section and link edit button to original form
1. Fill out creator profile form and navigate to last slide
* Any data display inconsistencies
> [Feat]: Add creator profile review slide

- frontend/src/components/common/NavBar.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfileForm.tsx
- frontend/src/types/CreatorProfileTypes.ts
[Edit Creator Profile Flow](https://www.notion.so/uwblueprintexecs/Edit-Creator-Profile-Flow-c509148b5b3d41979af6df1501bf9093?pvs=4)
* Add edit profile button to the nav for creator accounts
* Sent state along with router push to set the current page for the form to the review form
1. Click avatar in a creator profile, and edit button should appear and take you to the form
*
> [Feat]: Add edit creator profile button

- backend/typescript/rest/givecloud.ts
[Bug Subscriber Signup on Givecloud Fix](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=0f0df1f1b7074d2cb19b7eb7652d7d04&p=52a8549566c3452389e518960f028461&pm=c)
* changed the header name we get the hash from when comparing secret key
1.
*
> fixed header name change

- frontend/src/components/pages/CreatorProfile/Publications Form/PublicationsForm.tsx
[Publications validation on creator form](https://www.notion.so/uwblueprintexecs/Publications-validation-on-creator-form-confirm-w-soha-9798d6992764414aa0680e005b0aea67)
* Changed wording
1. Go to http://localhost:3000/create-creator-profile
2. Click the "Next" button until you're on Step 4: Publications
*
> Publications validation on creator form

- frontend/src/components/pages/CreatorProfile/AvailabilityForm.tsx
[General availability validation](https://www.notion.so/uwblueprintexecs/General-availability-validation-6f2edd3dbaa442c887d9c30695732124?pvs=4)
* Added span to conditionally render if creator profile availability is empty
1. Navigate to `/create-creator-profile` endpoint and click through to the Availability Form
2. Attempt to submit the form when availability is empty
3. Text will pop-up under the General Availability section prompting the user to enter their availability
*
> Add validation for General availability

- frontend/src/components/pages/CreatorProfile/WorkshopFormContainer.tsx
- frontend/src/constants/Routes.ts
[Highlight In Person/Remote button ](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=0f0df1f1b7074d2cb19b7eb7652d7d04&p=14cc4b28ba07416cb248168edb76288b&pm=c)
* Added states isVirtual and isInPerson as booleans, when each button is clicked, their respective states change. This alters whether they are highlighted or not
* Created a component for this button since it is the same thing duplicated. Possibility to duplicate this entire section to be honest.
* Each button has a respective input. I disabled the input until the button is clicked. I think this would be better for UX.
* Screenshots are on the Notion ticket
1. Go into this branch and run docker-compose up
2. Login as a creator and go to localhost:3000/create-creator-profile
3. Click "Next" until you get to …
> highlight in-person and remote button

- frontend/src/components/pages/CreatorProfile/CreatorOverview.tsx
[Creator overview fixes](https://www.notion.so/uwblueprintexecs/Creator-overview-fixes-a9d0199276ed4029b7c63e83c7bc8de6)
- For craft, split the string so each of them renders their own badge
- For genre, fixed casing
- Removed html tags from website
1. Go to creator profile
*
> Creator overview fixes

- backend/typescript/rest/creatorRoutes.ts
- backend/typescript/rest/genreRoutes.ts
- frontend/src/components/common/NavBar.tsx
- frontend/src/components/pages/CreatorDirectory/SearchCreators.tsx
[Nav Bar fixes](https://www.notion.so/uwblueprintexecs/Nav-Bar-fixes-83a088db7cc84bf6bd74202307b9b6fa?pvs=4)
* Add NavBar to creator directory page
* Show Login button in NavBar dropdown when user is not logged in
1. Navigate to `/creator-directory`
*
> Navbar Fixes
