- README.md
None
* Replaced docker exec commands with equivalent compose commands. Docker will now find container mapped to specific service name (ie. ts-backend) rather than using the container name.
1. Test all these commands after running `docker-compose up -d`
* Make sure all the commands works as expected
> updated docker exec commands in README

- backend/typescript/rest/reviewRoutes.ts
- backend/typescript/rest/tagRoutes.ts
[Review Service: Add Middleware](https://www.notion.so/uwblueprintexecs/Review-Service-Add-Middleware-92f6804588e2492083943261fd121413)
* Added `isAuthorizedByRole` middleware to review and tag endpoints
* Modification of reviews or tags (create, update, delete) requires "Admin" role
* Other endpoints require any ("Admin", "Subscriber", "Author") role
1. Make requests to any review or tag endpoint (e.g. `POST /reviews/`, `GET /tags/`) with/without a valid access token
> add role auth middleware to review and tag service endpoints

- frontend/src/APIClients/ReviewAPIClient.ts
- frontend/src/APIClients/TagAPIClient.ts
- frontend/src/constants/AuthConstants.ts
- frontend/src/utils/AuthUtils.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=f65b6bd2d905433a97458d1bc3b9cf05)
* Originally, the bearer token was stored as a const, which did not get updated from the local storage without a page reload
* Created a function to programatically fetch the token from local storage on every request
1. Clear local storage or open a new incognito window
2. Navigate to login page, login as usual
3. Open inspect console/developer tools
4. Navigate to the admin dashboard and ensure it gets populated without a page refresh
* Code correctness
* Is `AuthUtils.ts` a good place to put this function?
> Fix getting auth token without page refresh

- frontend/src/components/pages/CreateReview/BookModal.tsx
[Ticket Name](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=4e4dfe6d1ea342ac9679c151e8c9a3ba
* The price string was being spliced for some reason, removed this
1. Go to the create review page, open the "add book" modal
2. Fill in all fields, enter an integer price
3. Click save
4. Click the book you just added to re-open the Book Modal
5. You should see the price you entered
6. Publish the review and come back to edit it
7. Open an existing book's modal, you should see the book's price
* Why were we taking the substring in the first place?
> Fix bug where price in Book Modal is NaN

- frontend/src/components/pages/CreateReview/CreateReview.tsx
[Can add review with no books (Frontend)](https://www.notion.so/uwblueprintexecs/Can-add-review-with-no-books-Frontend-4b95a7be3b03480c827233e83da75b64)
* Added a check to disable the submit review button if the review doesn't have any books associated with it
1. Go to `/create-review`
2. Delete the book present
3. Verify that the Publish button is disabled 
*
> [Hotfix] Disable Review Submission Without Books Entry

- frontend/src/components/pages/CreateReview/AddNumberInput.tsx
- frontend/src/components/pages/CreateReview/BookModal.tsx
[Age range field ](https://www.notion.so/uwblueprintexecs/Age-range-field-e27580186fc74348a7408eb7cf3c4a53)
* Voted for better UX design. Now upon deleting a number field we can see it as empty instead of NaN
1. Navigate to the Admin Dashboard 
2. Either click “Add Review” or edit an existing review
3. Either click “Add Book”, or if editing, click an existing book
4. Add an audience age range of any value then delete it (for both min and max), min and max fields should be empty instead of displaying NaN  
5. Fill in all other required fields, put 0 as the min audience age range, some value >0 as the max audience range
6. Try to click save, you should be able to save
* The Modal works as intended, can have a min age of 0, and do not see NaN display upon deletion of age. Can not submit form …
> Age range field bug fix

- frontend/src/components/pages/CreateReview/AddStringInput.tsx
- frontend/src/components/pages/CreateReview/BookModal.tsx
[Allow dashes in the ISBN field](https://www.notion.so/uwblueprintexecs/Allow-dashes-in-the-ISBN-field-0ac9ac6270684d19b8e6b0639c4b587e)
* 
ISB can now have only numbers and dashes with no 13 digit limit and can not have letters.
Added a regex pattern field to the form so that in the future we can use regex to filter out inputs appearing on the form
1. Admin Dashboard -> Create review 
2. Add a book
3. Play with the isb field, attempt adding dashes and numbers (should work),  attempt to add letters or other symbols (should not work)
4. Should be able to fully publish given the isb field is filled properly (and so are the other fields)
The ISB field working as intended and filtering unwanted input
> fixed ISB to include numbers and dashes

- frontend/src/components/PreviewReview/PreviewReviewModal.tsx
[Preview displays “draft” for published reviews](https://www.notion.so/uwblueprintexecs/Preview-displays-draft-for-published-reviews-d736f8cd836b44af8ef54923f8d96e93)
*  Checked if the published_at data field for Review is undefined or null
* If undefined or null, the preview Modal header displays "draft"
* Otherwise, displays "published"
1. Go to the admin dashboard
2. If a book review does not exist, publish one 
3. click the preview button (eye), in the top left corner: "Previewing" should say published if the review is published
4. Since draft reviews cannot be previewed yet, change the data field for published_at to null and tests that the book review says "Draft"
*
> Fix bug with preview modal header

- frontend/src/components/common/InviteAdminModal.tsx
[Invite an admin form does not clear](https://www.notion.so/uwblueprintexecs/Invite-an-admin-form-does-not-clear-d67d2f2a0c9a4df68a171eeb1bc0879f)
*  Cleared the states of all hooks so the invite admin form clears next time you open it and it doesn't always show that it was submitted successfully even though it was not. 
1. Invite a new admin > enter forms > submit successfully > invite a new admin 
check that the fields are now clear 
2.  invite a new admin > enter forms > submit successfully > invite a new admin > type invalid email address 
check that it shows the error toast
*
> fix bug where invite admin fields do not clear

- frontend/src/components/pages/CreateReview/CreateReview.tsx
- frontend/src/components/pages/CreateReview/SaveDraftReviewModal.tsx
[Save as Draft](https://www.notion.so/uwblueprintexecs/Save-as-Draft-2ae931bde8ec4ccea095ae0ff8bdb276)
*  Save as draft now works as intended
*  Pop up before leaving the page with a draft not saved in progress will be saved for a later ticket
A)
1. Go to Admin dashboard 
2. Create a review
3. Partially or fully complete a review
4. Press save as draft
5. Should redirect you back to Admin dashboard and save the review as a draft
B)
1) Try editing an already published review
2) Save as a draft
3) Should appear as a draft now
> [Feat] Save as Draft

- backend/typescript/services/implementations/reviewService.ts
[Publish Crashes when Adding an Empty Illustrator and/or Translator](https://www.notion.so/uwblueprintexecs/Publish-Crashes-when-Adding-an-Empty-Illustrator-and-or-Translator-443728d5526548a39227926eb6100ded)
* turns out it wasn't a problem with adding empty illustrators/translators, but a problem with if the minimum age and maximum age are the same
* this is because we create a Range object composed of [minimum age, maximum age] and by default, it's set to [) (inclusive min, exlusive max) https://sequelize.org/docs/v6/other-topics/other-data-types/ 
1. create a review with a new book with empty illustrator/translator and min/max age different and publish it
2. create a review with a new book with empty illustrator/translator and SAME min/max age and publish it
3. create a review with a …
> [Bug] Publish Crashes when Adding an Empty Illustrator and/or Translator

- frontend/src/components/PreviewReview/PreviewReview.tsx
[Books in Review are misordered](https://www.notion.so/uwblueprintexecs/Books-in-Review-are-misordered-e6ddddcd2dfd472f999bd1f41ca987f0)
* Sorted the book array according to their series order
Add a Review with multiple Books, and set different `seriesOrder` s for each Book (try setting it randomly for each book, so its not in order chronologically). On the Add Review Page, the Books should be sorted by their series order. Publish the review, open the preview component, and check that:
1. The books are sorted according to their order in the series
* checking that the books show up in correct order based on their series number no matter what order they were added in
> [Bug] fix bug with misordered books in preview modal

- backend/typescript/rest/reviewRoutes.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=ba309590ef8f4099b3603e9d7e79a267)
* Moved the auth validator middleware to be ahead of request validator
1. Open Postman/any REST client
2. Send an unauthenticated `POST` to `/reviews` with any/blank body. (Just don't fill in the authorization header)
3. You should get a `401` status code with an "unauthorized" message
* Any potential side-effects of doing this (ie test both unauthenticated and authenticated requests to make sure)
> [Bug] Don’t Validate Response Bodies with Invalid Auth

- backend/typescript/migrations/20220713231135-add-createdAt-updatedAt-to-book-genre-and-book-tag.js
Sequelize models expect tables they reference to have createdAt and updatedAt Date fields (fetched implicitly) Added a migration that adds these fields to `book_genre` and `book_tag` should they not exist
1. Run the up migration
2. Verify `createdAt`, `updatedAt` columns exist
3. Login to the platform and try a bunch of things
a. Add reviews,
b. Delete reviews,
c. Edit reviews, try modifying a bunch of fields
4. Run the down migration
5. Verify those two columns got removed
*
> Add sequelize-mandated timestamps to book_genre and book_tag tables

- frontend/src/components/pages/CreateReview/CreateReview.tsx
[Delete doesn't work from review page](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=e33929e2f17242ba8e33ff3f609b3a6e)
* Added delete review function that deletes review by id if user is editing a review and navigates back to dashboard
* otherwise, if user is creating a new review and deletes it, user is just redirect to dashboard
1. Edit an existing review and click the trash icon beside publish to delete it. Verify that it deletes.
2. Create a new review but do not publish. Click the trash icon to delete it and verifies it navigates back to dashboard.
*
> [Bug] Delete from review page

- backend/typescript/services/implementations/reviewService.ts
Old deleteReview broke when deleting last book in series. It would not delete it from the Series table because of async shenanigans leading to the transaction being committed before it could delete.
> [Tech] Refactor deleteReview

- backend/typescript/migrations/20220715012943-change-book-tag-book-genre-constraints-to-cascade.js
- frontend/src/APIClients/ReviewAPIClient.ts
- frontend/src/components/pages/AdminDashboard/AdminDashboard.tsx
[Ticket Name](https://www.notion.so/uwblueprintexecs/Change-book_tag-book_genre-constraints-to-cascade-d7faff9b64b848bea8ecd739b3f80b86)
This PR solves 2 issues:
* This causes deleting to fail (ie fk constraint violation)
* Migrated the constraints to support cascade on delete/update
1. Add 2 reviews containing books with Tags or Genres (maybe checkout #136 to do this using Postman)
2. Checkout this branch
3. Try deleting a review, it fails
4. Run migrations up
5. Deleting that added review should work
6. Run migrations down
7. Try deleting a review, it should fail again
* Make sure everything's spelt properly in the migration lol
> [Tech] Change book_tag, book_genre constraints to cascade

- backend/typescript/services/implementations/reviewService.ts
- backend/typescript/services/interfaces/IReviewService.ts
- backend/typescript/services/interfaces/checkers/IReviewService-ti.ts
* Defaulted tags/genres to [] if not supplied and made fields optional
1. Publish a review (on this branch)
2. Edit a review
*
> [Fix] Make tags, genres optional fields in ReviewRequest

- frontend/src/components/PreviewReview/PreviewReviewModal.tsx
- frontend/src/index.css
[Preview Review Modal overflows screen when review is too long](https://www.notion.so/uwblueprintexecs/Preview-Review-Modal-overflows-screen-when-review-is-too-long-f44d77645247499dba83e1f1085c8a39)
* Add an overflow css to allow for a scroll bar if the review is too big
1. Create a really long review
2.  Preview it in admin dashboard
3. Should now be scrollable and should only scroll the modal
* The review renders properly, and only the modal scrolls not the page
> [Bug] fixed preview overflow in admindashboard

- frontend/src/components/common/CircleBadge.tsx
- frontend/src/components/pages/MockSearch/MockSearchPage.tsx
- frontend/src/components/pages/MockSearch/ReviewThumbnail.tsx
- frontend/src/components/pages/MockSearch/ReviewsGrid.tsx
- frontend/src/components/pages/MockSearch/mockReviews.ts
- frontend/src/theme/index.tsx
[Grid of Reviews Component](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=fd4d68a50c9947da8a1e3a21582fad5f)
* Made responsive grid for desktop/mobile view
* Also added a badge displaying number of additional books in a review from this last ticket (https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=73b75f1d3b8f4901a8e565445fcc554b) I forgot to implement
1. Go to http://localhost:3000/test/mock-search-page
2. Change different viewports and verify that grid is responsive (go to inspect console and choose different mobile views)
3. Also verify that badge displaying +number is displaying the correct number of books.
Video demo: …
> [Feat] Grid of Reviews Component

- frontend/src/components/PreviewReview/PreviewReview.tsx
[Add Tags/Genres to Book Previews](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=57fe0869572345a3a80eca4eecb5b71c&pm=c)
* Add Tags/Genres to Book Previews
1. add/edit/remove genres/tags and preview
> [Feat]: Add Tags/Genres to Book Previews

- backend/typescript/middlewares/givecloud.ts
- backend/typescript/middlewares/validators/givecloudValidators.ts
- backend/typescript/rest/givecloud.ts
* Added a variable to the env file (not pushed)
* Used that variable and double checked with the authorization sent from a post request to make sure they are the same other wise we return a 400 error, and do not proceed further
1. Send a request to the givecloud endpoint without an authorization (should return a 400 erro)
2. Send a request to the givecloud endpoint with the correct authorization key but wrong value (400 error)
3. Send a request to the givecloud endpoint with the correct key and value (goes through)
> [Feat] Made givecloud private by an env variable

- frontend/src/components/pages/SearchReviews/ReviewThumbnail.tsx
- frontend/src/components/pages/SearchReviews/ReviewsGrid.tsx
[Genre on Book Thumbnail](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=ca31ba03cb10475cb4165fb80f49577d&pm=c)
* if one book take first genre
* if multiple books, find most frequent genre
1. create review with one/multiple genres
2. verify the correct genre shows in search
> [Feat]: Genre on Book Thumbnail

- backend/typescript/models/book.model.ts
- backend/typescript/services/implementations/reviewService.ts
[Age is not previewing correctly](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=25eb2d7845e74b12b19debbf386ddbc6&pm=c)
* throw in a `-1` because sequelize stores 3-6 inclusive as [3-7)
1. Add book with age range, verify age range in preview
> [Bug]: Age is not previewing correctly

- frontend/src/components/PreviewReview/PreviewReview.tsx
[Book Preview Sometimes Shows Illustrator Even if Blank](https://www.notion.so/uwblueprintexecs/Book-Preview-Sometimes-Shows-Illustrator-Even-if-Blank-b23e87f5ffc9412dac72c8cff4a2b2dc)
* Added check to ensure illustrator by field does not show up if there are no illustrators
1. Create a book and leave illustrator section like this:
2. Check that in book preview, there is no illustrated by section
*
> [Bug] Fix Blank "Illustrated by" field in Book Preview

- frontend/src/components/PreviewReview/PreviewReview.tsx
[Add Price to Book Review](https://www.notion.so/uwblueprintexecs/Add-Price-to-Book-Review-df963de68c414a908a3bb1569c462a22)
* add price behind book format in review and preview review pages
1. check that price is there in preview review page
2. check that price is there in review page
*
> [Feat] Add price to review page

- frontend/src/components/common/InviteAdminModal.tsx
[Loading Spinner for Invite New AdminPreviewReviewModal](https://www.notion.so/uwblueprintexecs/Loading-Spinner-for-Invite-New-AdminPreviewReviewModal-13d039bb01f0476a93df0d58e7925a67)
* added loading spinner after user submits form
https://user-images.githubusercontent.com/75541476/190526365-b49951e1-bafd-461c-95e3-1b081696003b.mov
1. Go to localhost:3000 and login
2. Click profile icon > Invite new admin
3. Spinner should show when you hit submit
*
> [fix]: add loading spinner to invite admin modal

- frontend/src/components/PreviewReview/PreviewReview.tsx
[Previewing a Single Book](https://www.notion.so/uwblueprintexecs/Previewing-a-Single-Book-f510c07114eb4de9b153971f1305bf9f)
* To hide nav arrows and coloured dots for single books (ie not a book series), I used conditional rendering with review.books.length to check if it was a single book and render/hide the appropriate components.
1.  Go to Admin Dashboard
2. Preview a review (click the eye)
3. Check both book series and single books. Single books should not have arrows or dots but the spacing should be the same as book series. For a visual, view the ticket on notion. The highlighted areas in the photo should not be visible for single books.
* Correct implementation & DRY as much as I can
> bug: hide nav arrows and coloured dot for single books

- backend/typescript/rest/reviewRoutes.ts
[Block Subscribers from Viewing Drafts](https://www.notion.so/uwblueprintexecs/Block-Subscribers-from-Viewing-Drafts-3789f3e949c14c78a132983a91eee967)
* Use auth service to check a user's role when they are attempting to view an individual draft. Also filter out drafts when users are not admins and they hit `/reviews`
1. Seed database with drafts and published reviews
2. Make an admin account & non admin account
3. Attempt to view a draft as admin and non admin by `/review/:id`. The non admin should get a 404 and the admin should get the draft
4. View all the results in `/reviews`. For a non admin drafts should be filtered out but pages should still have full capacity (filtering should be done BEFORE pagination). For admins they should simply recieve all reviews.
* Code style. This is my …
> Block Subscribers from Viewing Drafts

- frontend/src/components/pages/SearchReviews/SearchReviews.tsx
[Going Back to Search Page doesn’t apply search/filter query properly](https://www.notion.so/uwblueprintexecs/Going-Back-to-Search-Page-doesn-t-apply-search-filter-query-properly-c9e5392b712146efa85df701fe3f34b5)
*  Use the loading hook to make sure that the reviews does not update twice
* Set the loading hook to true at first, and not call the review API without rendering the URL search params
1. Search for something
2. Observe the returned results
3. Click on a review
4. Click on “Go Back”
5. The search box will still be pre-filled with the search query from earlier, but the results will not match that search query
6. Refreshing the page fixes it
* Try the search with various books
> [Bug] Apply search when going back to search page 

- backend/typescript/migrations/20220715012943-change-book-tag-book-genre-constraints-to-cascade.js
- backend/typescript/seeders/2022.09.29T23.08.12.sample-genres.ts
- backend/typescript/seeders/2022.09.29T23.22.12.sample-book-genres.ts
[BUG: Intersecting age intervals](https://www.notion.so/uwblueprintexecs/BUG-Intersecting-age-intervals-08ba73a0e5c84f67b507989057ea88c1)
* The age bug was actually an error with a missing genres and book_genres table so this ticket instead adds seeding scripts to fill the table
1. Visit the home page
2. Ensure books are visible for age 4-8 and 9-12 but not 0-3
* Anything unusual with details of the seeding script
> [Fix]: add genre seeding scripts

- backend/typescript/middlewares/validators/userValidators.ts
- backend/typescript/rest/userRoutes.ts
[Broken email verification for non-admin user](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=f995dbc4dd314a8a82c31785425deeba&pm=c)
* rerouted post method of creating a non-admin user to use the same set of functions as creating a new admin
1. Create a non-admin user through the post route in userServices
2. Click on the email link and see if it goes through the signup process flow as usual
* Changed function for handling post route "/"
https://user-images.githubusercontent.com/55671206/194438333-4cfb5c7e-f131-4f20-8027-c14125df3e9a.mov
https://user-images.githubusercontent.com/55671206/194438510-39ec9c89-eaf9-441b-ab71-4c0cdc68fcb3.mov
> [FIX]: Fixed email verification for non-admin users

- backend/typescript/middlewares/auth.ts
- backend/typescript/rest/authRoutes.ts
- frontend/src/APIClients/AuthAPIClient.ts
[Close user registration route to admins only ](https://www.notion.so/uwblueprintexecs/Close-user-registration-route-to-admins-only-251b4e1ff7014ea6bb514db89f5754a5)
* Added isAuthorizedByRole as middleware for the register route 
1. Test that you can register other uses with an admin user
2. Test that you cannot register other users with any other role
*  the response code
> [Feat] Close user registration route to admins only 

- frontend/src/components/PreviewReview/PreviewInfo.tsx
- frontend/src/components/pages/CreateReview/BookModal.tsx
- frontend/src/components/pages/SearchReviews/mockReviews.ts
- frontend/src/types/BookTypes.ts
- frontend/src/types/ReviewTypes.ts
[Unordered and Ordered Series](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=aedc8d99cd8b437cb556ece10f3c0e3c&p=3b3ba30ae8054e92a5cb9009f7ff8aa5&pm=c)
* changes seriesOrder prop for book type where 0 means it is unordered and any other number indicates its order in the series
default behaviours:
* if ordered button is selected, series name and series number become required fields in the form
* if ordered button is deselected, the series order for that book is set to 0 and series name is no longer a required field
1. Create a book review
2. Fill in required fields
3. Toggle on Ordered Field and see if form is submittable without Series Name and Order
Unordered Series
Ordered Series
* the default behaviours I described above might not be how we want it to act
> [Feat]: Added ordered/unordered series for books

- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/authService.ts
[Invalidate tokens for expired subscriptions](https://www.notion.so/uwblueprintexecs/Invalidate-tokens-for-expired-subscriptions-9dc0cf5a7b184fb9828b01bd2b479e52)
Check if the subscription expiry date is earlier than current date on refresh and if it is, revoke the token.
1. Login with an admin user account
2. Make a put request to the /users/:userid with your id with the subscription day earlier than current date (some changes to the put route and uservalidators may need to be made for this put request to work)
3. Make a post request to /auth/refresh
4. Check that the token is revoked
> revoke keys based off of subscription expiry date

- frontend/src/components/pages/CreateReview/CreateReview.tsx
[Bug Fix Alert](https://www.notion.so/uwblueprintexecs/Save-Draft-Pop-Up-Alert-b1059a4faad44538bf9a30bdf6333c5f)
* Used window event and handled new data. Connected with already implemented components.
* One issue is if they do not make any changes, the pop up will still appear. I think the `cannotSave` variable does not actually work as the Save button is never disabled. Hence, I believe there might be an issue in this which also propogates to this case. Not sure if this is a blocking issue. [FIXED]
> Save Changes Alert Bug Fix

- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/creatorService.ts
- backend/typescript/services/interfaces/creatorService.ts
- frontend/src/App.tsx
- frontend/src/components/pages/CreatorProfile/FinishProfileLanding.tsx
- frontend/src/constants/Routes.ts
[Creator “Finish Profile” flow](https://www.notion.so/uwblueprintexecs/Creator-Finish-Profile-flow-736d5955d5e94b31ae491dd65899d8e2)
* added send email function as described in ticket + new page for directing to the create profile flow
1. call verify email route using creator profile (once sign up route completed)
2. visit localhost:3000/finish-profile
*
> [Feat]: add creator finish profile flow

- frontend/src/App.tsx
- frontend/src/components/pages/CreatorProfile/ContactInfoForm.tsx
- frontend/src/components/pages/CreatorProfile/CreatorInputField.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfileForm.tsx
[Creator Profile: Setup + Contact Info Form](https://www.notion.so/uwblueprintexecs/Creator-Profile-Setup-Contact-Info-Form-4dbbb2da01234060ae7bcf5ea1b8d6ef)
* As mentioned in ticket, added a new CreatorProfileForm component and set up a 'Tab' system to navigate between each stage of form
* Added first form, contact info that stores all info into state in the original creator profile form
1. Visit `create-creator-profile` page and navigate to other tab
> [Feat]: Add creator info form setup + contact info form

- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/App.tsx
- frontend/src/components/auth/CreatorSignup.tsx
- frontend/src/components/auth/EmailForm.tsx
- frontend/src/components/auth/SubscriberSignup.tsx
- frontend/src/constants/Routes.ts
[Creator Signup](https://www.notion.so/uwblueprintexecs/Creator-Signup-e0687bd83429497d9d633a546d10be1b)
* Pulled out email form from SubscriberSignup to be a reusable component
* -Created new CreatorSignup component
* Added 'creator-registration' route to the CreatorSignup component
1. Go to localhost:3000/creator-registration
2. Input email and press the sign up button
3. There is no success feedback for a successful response, heck your email to ensure a link has been sent
* frontend/src/components/auth/EmailForm.tsx: 9. Is there a better way to do the type interface for a useHook function? As well is there a way that we do not need to pass in the isEmailInvalid, and setIsEmailInvalid into the EmailForm component?
* The CreatorSignup component currently uses the exact Subscriber signup …
> Add Creator Signup

- frontend/src/components/pages/CreatorProfile/ContactInfoForm.tsx
- frontend/src/components/pages/CreatorProfile/CreatorInputField.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfileForm.tsx
- frontend/src/contexts/CreatorProfileContext.ts
- frontend/src/types/CreatorProfileTypes.ts
[Creator Profile: Setup + Contact Info Form](https://www.notion.so/uwblueprintexecs/Creator-Profile-Setup-Contact-Info-Form-4dbbb2da01234060ae7bcf5ea1b8d6ef)
* Follow up from previous to refactor instead of passing several state variables, instead using a creatorProfileContext for the creator object throughout the form pages 
1.
*
> [Refactor]: Swap useState for useContext for creator profile form

- frontend/src/components/pages/SearchReviews/SearchReviews.tsx
[Audience Filter](https://www.notion.so/uwblueprintexecs/Audience-Filter-a372c5269ee64535b2c8a956411d9715?pvs=4)
* Update logic to use hardcoded options for the audience age ranges instead of the reviews that are shown
1. Proceed to Magazine Directory > Search and test filters - with seed data age 0-3 should show no results and all other filters should show all reviews (query also shown in url)
* Want to confirm filtering requirements - does 3-17 mean it should be included in the 0-3 section?
* Are those the required age ranges? `["0-3", "4-8", "9-12", "12-18"]`
> refactor audience review filter

- backend/typescript/rest/creatorBookingRoutes.ts
- frontend/src/APIClients/CreatorAPIClient.ts
- frontend/src/components/pages/CreatorProfile/ContactInquiry.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfile.tsx
- frontend/src/types/CreatorTypes.ts
[Booker: Creator Contact Form](https://www.notion.so/uwblueprintexecs/Booker-Creator-Contact-Form-cba202d29f044821afae57b6e92ae5a7?pvs=4)
* Display CreatorInquiry form with corresponding Creator data as a modal when a user clicks the Contact button 
* Load profile picture link, added creator full name and craft + related styling
1. Access a creator using the endpoint `creators/{creator_id}` 
2. Click on the contact form
3. Run though the CreatorInquiry form flow and submit 
4. Clicking the 'x' button will display a confirmation about the exit 
* Use of useDisclosure to control the modal display of the CreatorInquiry form
* Is creator.craft representative of the creator role? 
* Added a TODO comment about where to send the CreatorInquriy form data on submit
> Add CreatorInquiry form modal to CreatorProfile 

- frontend/src/components/common/NavBar.tsx
[Empty Account Dropdown](https://www.notion.so/uwblueprintexecs/Empty-Account-Dropdown-0571841bd98e41a7b124f2d95414f1c3?pvs=4)
* Removed some checks that were causing the account values to not populate
* Display email and change password option for all users instead of just admin
* Display role type for all users
1. Login with an account and click on the account button in the navigation bar
* When newly creating an account, the user first name and last name fields will be empty since we only ask for email on signup. So, the first name and last name will not display on the account dropdown on a newly created account
> Fix empty account dropdown

- backend/typescript/rest/creatorRoutes.ts
- frontend/src/APIClients/BaseAPIClient.ts
- frontend/src/constants/Routes.ts
[Constant reload ](https://www.notion.so/uwblueprintexecs/Constant-reload-dd396e31688d445c8f51ac5c8105b0ef)
* Removed auth check on the creator route for GET by ID
* Reworked BaseAPIClient to not redirect if there is no jwt token on creator/id page. Any other page should be redirected to /login if the jwt token is expired.
1. Run docker-compose up
2. Double check database is seeded
3. Without signing in, go to http://localhost:3000/creators/1
4. Check if you can access the page and all the data loads
* Is it safe to remove the authorization check for the GET by ID route?
> Fix Constant Reload Bug

- frontend/src/components/pages/CreateReview/BookModal.tsx
- frontend/src/components/pages/CreatorProfile/AddProfilePictureField.tsx
- frontend/src/components/pages/CreatorProfile/GeneralInfoForm.tsx
- frontend/src/components/pages/CreatorProfile/RichTextEditorField.tsx
- frontend/src/types/Types.ts
[Image Upload for Books](https://www.notion.so/uwblueprintexecs/16fb020b93f641c8b384f76a1b3c769e?v=0f0df1f1b7074d2cb19b7eb7652d7d04&p=c9cc366e6a1a463daad7625e3d42d8e8&pm=c)
* Added a mode selector for the addprofilepic component to support bookmodal for this component
* Replaced the book cover URL text component with addprofilepic
1. Signup as an Admin in `localhost:3000/signup`
2. Go to `localhost:3000/create-review`
3. Click the plus sign to add a book cover and upload an image
4. Fixed styling errors related to width of component in `GeneralInfoForm`
* Better way to build the mode selector
* Does the image upload properly?
> replace import image field to bookmodal vs image URL

- frontend/src/components/pages/MagazineReview/MagazineReview.tsx
[12+ Category](https://www.notion.so/uwblueprintexecs/12-Category-263b405b65c6435ebcad563003aea3d8?pvs=4)
* Added a 12+ category for the magazine review landing page
* Updated background position so bottom of page isn't blank
* Updated reviews per section to fit Figma + page width
1. Open Magazine Directory tab and scroll to bottom
* Is there anywhere else this needs to be updated? Confirmed categories exist for magazine filtering + creator filtering
* Noticed the magazine filter uses 12-18 while creator filter uses 12-100 should one of these be chosen for consistency?
> Add 12+ category to magazine reviews

- backend/typescript/rest/creatorRoutes.ts
[Save and exit fails on staging](https://www.notion.so/uwblueprintexecs/Save-and-exit-fails-on-staging-ac1659f6ad08492f90e22cb1550b39b5?pvs=4)
* Bug was because numeric user_id was being sent as a string - this parses it into an int before looking up the creator
* Tested locally with new creator and cleared database and saved successfully
1. Create new creator profile + try to save 
*
> [Bug]: Fix userId param

- frontend/src/components/pages/AdminDashboard/AdminCreatorProfiles.tsx
[Link Admin Dashboard to Creator Profile](https://www.notion.so/uwblueprintexecs/Link-Admin-Dashboard-to-Creator-Profile-bebe3cd1c01d4c7a918aa6b19f7a031f?pvs=4)
* Added custom render for creator name into button that links to profile
1. Navigate to creator page on admin dashboard + click on creator name
*
> [Fix]: link creator dashboard to profile

- frontend/src/components/pages/MagazineReview/MagazineReview.tsx
[Only subscribers should see the prompt to renew their subscription](https://www.notion.so/uwblueprintexecs/Only-subscribers-should-see-the-prompt-to-renew-their-subscription-393544d5b05e46ac822f557c9ed5cc0d?pvs=4)
* Added isSubscriber flag to determine whether the modal should pop up
* Removed dependency from useEffect that was causing infinite requests (and confirmed modal still pops up without the dependency) 
1. Login as admin and modal shouldn't pop up anymore
*
> [Bug]: Remove subscription notice for admins

- backend/typescript/services/implementations/creatorService.ts
[Display date section properly in admin dashboard](https://www.notion.so/uwblueprintexecs/Display-date-section-properly-in-admin-dashboard-5c057337488f4b7e91947454c7079311?pvs=4)
* The getCreators function wasn't returning the createdAt field so it was undefined and not showing up
1. Go to the creator profile admin dashboard and there should be a date now
*
> add createdAt to api response

- frontend/src/components/pages/CreatorProfile/CreatorPresentations.tsx
- frontend/src/components/pages/CreatorProfile/CreatorPublications.tsx
[Hide publications + presentations section if there’s no publications/presentations](https://www.notion.so/uwblueprintexecs/Hide-publications-presentations-section-if-there-s-no-publications-presentations-03b3dc77c7704e22b1e6ba0e23fbbe68)
* Publications and presentations each conditionally render now based on whether there are actually any publications or presentations respectively
1. Go to creator profile
*
> Hide publications and presentations when none exist

- frontend/src/components/pages/CreatorProfile/CreatorProfileForm.tsx
- frontend/src/components/pages/MagazineReview/MagazineReview.tsx
- frontend/src/components/pages/Subscription/SubscriptionExpireModal.tsx
[Block creators if their subscription is expired](https://www.notion.so/uwblueprintexecs/Block-creators-if-their-subscription-is-expired-a589552dbf3e414c955888cdf7685013?pvs=4)
* Created new SubscriptionExpireModal component using the logic from the MagazineReview component with a prop to determine which user is affected
* Implemented this in MagazineReview for subscribers and CreatorProfileForm for creators 
1. Login in as creator with expired subscription and visit `/create-creator-profile`
*
> [Fix]: Add expired modal for creator flow

- frontend/src/components/pages/CreatorProfile/Carousel.tsx
- frontend/src/components/pages/CreatorProfile/CreatorProfile.tsx
- frontend/src/components/pages/CreatorProfile/CreatorPublications.tsx
[Image to carousel in publications](https://www.notion.so/uwblueprintexecs/Image-to-carousel-in-publications-ba4ea61368cd44e2b65c0dff4cd91d97?pvs=4)
* Added carousel for images if # of images > 3 similar to publication data display
1. Create a creator with > 3 images
2. Submit + approve them
3. Visit creator directory page
*
> add carousel for publication images
